import { createSlice, PayloadAction } from '@reduxjs/toolkit';

interface CountriesState {
  countries: string[];
}

const initialState: CountriesState = {
  countries: [
    'United States',
    'Canada',
    'United Kingdom',
    'Australia',
    'Germany',
    'France',
    'Japan',
    'China',
    'India',
    'Brazil',
    'Russia',
    'Italy',
    'Spain',
    'Netherlands',
    'South Korea',
    'Mexico',
    'Argentina',
    'Turkey',
    'Saudi Arabia',
    'South Africa',
    'Sweden',
    'Norway',
    'Finland',
    'Denmark',
    'New Zealand',
    'Belgium',
    'Switzerland',
    'Austria',
    'Ireland',
    'Poland',
    'Czech Republic',
    'Portugal',
    'Greece',
    'Hungary',
    'Israel',
    'Singapore',
    'Malaysia',
    'Philippines',
    'Indonesia',
    'Vietnam',
    'Thailand',
    'Bangladesh',
    'Pakistan',
    'Egypt',
    'Morocco',
    'Kenya',
    'Nigeria',
    'Colombia',
    'Chile',
    'Peru',
    'Ukraine',
    'Romania',
    'Iceland',
    'Slovakia',
    'Slovenia',
    'Lithuania',
    'Latvia',
    'Estonia',
    'Serbia',
    'Bulgaria',
    'Croatia',
    'Bosnia and Herzegovina',
    'Montenegro',
    'North Macedonia',
    'Algeria',
    'Angola',
    'Armenia',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Barbados',
    'Belarus',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Botswana',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde (Cape Verde)',
    'Cameroon',
    'Central African Republic',
    'Chad',
    'Comoros',
    'Congo, Republic of',
    'Congo, Democratic Republic of the',
    'Costa Rica',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Gabon',
    'Gambia',
    'Georgia',
    'Gh',
    'Ghana',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Italy',
    'Jamaica',
    'Jordan',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malta',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Mozambique',
    'Namibia',
    'Nauru',
    'Nepal',
    'Niger',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Qatar',
    'Russia',
    'Saudi Arabia',
    'Senegal',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Solomon Islands',
    'Somalia',
    'South Sudan',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Tajikistan',
    'Tanzania',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'United Arab Emirates',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Yemen',
    'Zambia',
    'Zimbabwe',
  ],
};

const countriesSlice = createSlice({
  name: 'countries',
  initialState,
  reducers: {
    addCountry(state, action: PayloadAction<string>) {
      state.countries.push(action.payload);
    },
    removeCountry(state, action: PayloadAction<string>) {
      state.countries = state.countries.filter(
        (country) => country !== action.payload,
      );
    },
  },
});

export const { addCountry, removeCountry } = countriesSlice.actions;
export default countriesSlice.reducer;
